import { Router } from "express";
import { authRouter } from "./auth.routes";
import { accountsRouter } from "./accounts.routes";
import { partnersRouter } from "./partners.routes";
import { vehiclesRouter } from "./vehicles.routes";
import { invoicesRouter } from "./invoices.routes";
import { paymentsRouter } from "./payments.routes";
import { zarveSyncRouter } from "./zarveSync.routes";
import { reportsRouter } from "./reports.routes";
import { revenueRecapRouter } from "./revenueRecap.routes";
import { driverRevenueRecapRouter } from "./driverRevenueRecap.routes";
import { zarveInvoicesRouter } from "./zarveInvoices.routes";
import { dashboardRouter } from "./dashboard.routes";
import { settingsRouter } from "./settings.routes";
import { zarveMirrorRouter } from "./zarveMirror.routes";
import { reconciliationRouter } from "./reconciliation.routes";
import { journalEntriesRouter } from "./journalEntries.routes";
import { vendorBillsRouter } from "./vendorBills.routes";
import { vendorPaymentsRouter } from "./vendorPayments.routes";

export const apiRouter = Router();

apiRouter.get("/health", (_req, res) => res.json({ status: "ok" }));
apiRouter.use("/auth", authRouter);
apiRouter.use("/accounts", accountsRouter);
apiRouter.use("/partners", partnersRouter);
apiRouter.use("/vehicles", vehiclesRouter);
apiRouter.use("/invoices", invoicesRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/zarve-sync", zarveSyncRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/revenue-recap", revenueRecapRouter);
apiRouter.use("/driver-revenue-recap", driverRevenueRecapRouter);
apiRouter.use("/zarve-invoices", zarveInvoicesRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/zarve-mirror", zarveMirrorRouter);
apiRouter.use("/reconciliation", reconciliationRouter);
apiRouter.use("/journal-entries", journalEntriesRouter);
apiRouter.use("/vendor-bills", vendorBillsRouter);
apiRouter.use("/vendor-payments", vendorPaymentsRouter);
