-- Client asked for the B2B chart of accounts to match a full reference COA exactly
-- (screenshot of a standard Indonesian accounting app's default account list) --
-- replaces the 18 placeholder seed accounts from 014_business_unit.sql (verified
-- unreferenced by any journal_lines/products/fixed_assets/stock_adjustments row) with
-- ~134 accounts across the same category system introduced in
-- 017_account_categories_and_taxes.sql, reusing the account_categories this asks for.

-- The reference COA needs two categories we don't have yet, plus the 5 asset
-- categories 033_relabel_account_categories.sql soft-hid (this COA uses them).
INSERT INTO account_categories (business_unit, value, label, type, code_hint)
VALUES
  ('b2b', 'dep_amort', 'Akumulasi Penyusutan & Amortisasi', 'asset', '17'),
  ('b2b', 'other_asset', 'Aset Lainnya', 'asset', '18');

UPDATE account_categories
SET is_active = 1
WHERE business_unit = 'b2b' AND value IN ('cash_bank', 'ar', 'inventory', 'other_current_asset', 'fixed_asset');

-- The 18 placeholder accounts are superseded wholesale by the reference COA below.
DELETE FROM accounts WHERE business_unit = 'b2b';

INSERT INTO accounts (code, name, type, business_unit, category_id)
SELECT v.code, v.name, v.type, 'b2b', c.id
FROM (
  SELECT '1-10001' AS code, 'Kas' AS name, 'asset' AS type, 'cash_bank' AS cat
  UNION ALL SELECT '1-10002', 'Rekening Bank', 'asset', 'cash_bank'
  UNION ALL SELECT '1-10003', 'Giro', 'asset', 'cash_bank'
  UNION ALL SELECT '1-10100', 'Piutang Usaha', 'asset', 'ar'
  UNION ALL SELECT '1-10101', 'Piutang Belum Ditagih', 'asset', 'ar'
  UNION ALL SELECT '1-10102', 'Cadangan Kerugian Piutang', 'asset', 'ar'
  UNION ALL SELECT '1-10200', 'Persediaan Barang', 'asset', 'inventory'
  UNION ALL SELECT '1-10300', 'Piutang Lainnya', 'asset', 'other_current_asset'
  UNION ALL SELECT '1-10301', 'Piutang Karyawan', 'asset', 'other_current_asset'
  UNION ALL SELECT '1-10400', 'Dana Belum Disetor', 'asset', 'other_current_asset'
  UNION ALL SELECT '1-10401', 'Aset Lancar Lainnya', 'asset', 'other_current_asset'
  UNION ALL SELECT '1-10402', 'Biaya Dibayar Di Muka', 'asset', 'other_current_asset'
  UNION ALL SELECT '1-10403', 'Uang Muka', 'asset', 'other_current_asset'
  UNION ALL SELECT '1-10500', 'PPN Masukan', 'asset', 'other_current_asset'
  UNION ALL SELECT '1-10501', 'Pajak Dibayar Di Muka - PPh 22', 'asset', 'other_current_asset'
  UNION ALL SELECT '1-10502', 'Pajak Dibayar Di Muka - PPh 23', 'asset', 'other_current_asset'
  UNION ALL SELECT '1-10503', 'Pajak Dibayar Di Muka - PPh 25', 'asset', 'other_current_asset'
  UNION ALL SELECT '1-10700', 'Aset Tetap - Tanah', 'asset', 'fixed_asset'
  UNION ALL SELECT '1-10701', 'Aset Tetap - Bangunan', 'asset', 'fixed_asset'
  UNION ALL SELECT '1-10702', 'Aset Tetap - Building Improvements', 'asset', 'fixed_asset'
  UNION ALL SELECT '1-10703', 'Aset Tetap - Kendaraan', 'asset', 'fixed_asset'
  UNION ALL SELECT '1-10704', 'Aset Tetap - Mesin & Peralatan', 'asset', 'fixed_asset'
  UNION ALL SELECT '1-10705', 'Aset Tetap - Perlengkapan Kantor', 'asset', 'fixed_asset'
  UNION ALL SELECT '1-10706', 'Aset Tetap - Aset Sewa Guna Usaha', 'asset', 'fixed_asset'
  UNION ALL SELECT '1-10707', 'Aset Tak Berwujud', 'asset', 'fixed_asset'
  UNION ALL SELECT '1-10751', 'Akumulasi Penyusutan - Bangunan', 'asset', 'dep_amort'
  UNION ALL SELECT '1-10752', 'Akumulasi Penyusutan - Building Improvements', 'asset', 'dep_amort'
  UNION ALL SELECT '1-10753', 'Akumulasi Penyusutan - Kendaraan', 'asset', 'dep_amort'
  UNION ALL SELECT '1-10754', 'Akumulasi Penyusutan - Mesin & Peralatan', 'asset', 'dep_amort'
  UNION ALL SELECT '1-10755', 'Akumulasi Penyusutan - Peralatan Kantor', 'asset', 'dep_amort'
  UNION ALL SELECT '1-10756', 'Akumulasi Penyusutan - Aset Sewa Guna Usaha', 'asset', 'dep_amort'
  UNION ALL SELECT '1-10757', 'Akumulasi Amortisasi', 'asset', 'dep_amort'
  UNION ALL SELECT '1-10800', 'Investasi', 'asset', 'other_asset'
  UNION ALL SELECT '2-20100', 'Hutang Usaha', 'liability', 'ap'
  UNION ALL SELECT '2-20101', 'Hutang Belum Ditagih', 'liability', 'ap'
  UNION ALL SELECT '2-20200', 'Hutang Lain Lain', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20201', 'Hutang Gaji', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20202', 'Hutang Deviden', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20203', 'Pendapatan Diterima Di Muka', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20205', 'Hutang Konsinyasi', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20301', 'Sarana Kantor Terhutang', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20302', 'Bunga Terhutang', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20399', 'Biaya Terhutang Lainnya', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20400', 'Hutang Bank', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20500', 'PPN Keluaran', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20501', 'Hutang Pajak - PPh 21', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20502', 'Hutang Pajak - PPh 22', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20503', 'Hutang Pajak - PPh 23', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20504', 'Hutang Pajak - PPh 29', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20599', 'Hutang Pajak Lainnya', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20600', 'Hutang dari Pemegang Saham', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20601', 'Kewajiban Lancar Lainnya', 'liability', 'other_current_liability'
  UNION ALL SELECT '2-20700', 'Kewajiban Manfaat Karyawan', 'liability', 'long_term_liability'
  UNION ALL SELECT '3-30000', 'Modal Saham', 'equity', 'equity'
  UNION ALL SELECT '3-30001', 'Tambahan Modal Disetor', 'equity', 'equity'
  UNION ALL SELECT '3-30100', 'Laba Ditahan', 'equity', 'equity'
  UNION ALL SELECT '3-30200', 'Deviden', 'equity', 'equity'
  UNION ALL SELECT '3-30300', 'Pendapatan Komprehensif Lainnya', 'equity', 'equity'
  UNION ALL SELECT '3-30999', 'Ekuitas Saldo Awal', 'equity', 'equity'
  UNION ALL SELECT '4-40000', 'Pendapatan', 'income', 'income'
  UNION ALL SELECT '4-40100', 'Diskon Penjualan', 'income', 'income'
  UNION ALL SELECT '4-40200', 'Retur Penjualan', 'income', 'income'
  UNION ALL SELECT '4-40201', 'Pendapatan Belum Ditagih', 'income', 'income'
  UNION ALL SELECT '5-50000', 'Beban Pokok Pendapatan', 'expense', 'cogs'
  UNION ALL SELECT '5-50100', 'Diskon Pembelian', 'expense', 'cogs'
  UNION ALL SELECT '5-50200', 'Retur Pembelian', 'expense', 'cogs'
  UNION ALL SELECT '5-50300', 'Pengiriman & Pengangkutan', 'expense', 'cogs'
  UNION ALL SELECT '5-50400', 'Biaya Impor', 'expense', 'cogs'
  UNION ALL SELECT '5-50500', 'Biaya Produksi', 'expense', 'cogs'
  UNION ALL SELECT '6-60000', 'Biaya Penjualan', 'expense', 'expense'
  UNION ALL SELECT '6-60001', 'Iklan & Promosi', 'expense', 'expense'
  UNION ALL SELECT '6-60002', 'Komisi & Fee', 'expense', 'expense'
  UNION ALL SELECT '6-60003', 'Bensin, Tol dan Parkir - Penjualan', 'expense', 'expense'
  UNION ALL SELECT '6-60004', 'Perjalanan Dinas - Penjualan', 'expense', 'expense'
  UNION ALL SELECT '6-60005', 'Komunikasi - Penjualan', 'expense', 'expense'
  UNION ALL SELECT '6-60006', 'Marketing Lainnya', 'expense', 'expense'
  UNION ALL SELECT '6-60100', 'Biaya Umum & Administratif', 'expense', 'expense'
  UNION ALL SELECT '6-60101', 'Gaji', 'expense', 'expense'
  UNION ALL SELECT '6-60102', 'Upah', 'expense', 'expense'
  UNION ALL SELECT '6-60103', 'Makanan & Transportasi', 'expense', 'expense'
  UNION ALL SELECT '6-60104', 'Lembur', 'expense', 'expense'
  UNION ALL SELECT '6-60105', 'Pengobatan', 'expense', 'expense'
  UNION ALL SELECT '6-60106', 'THR & Bonus', 'expense', 'expense'
  UNION ALL SELECT '6-60107', 'Jamsostek', 'expense', 'expense'
  UNION ALL SELECT '6-60108', 'Insentif', 'expense', 'expense'
  UNION ALL SELECT '6-60109', 'Pesangon', 'expense', 'expense'
  UNION ALL SELECT '6-60110', 'Manfaat dan Tunjangan Lain', 'expense', 'expense'
  UNION ALL SELECT '6-60200', 'Donasi', 'expense', 'expense'
  UNION ALL SELECT '6-60201', 'Hiburan', 'expense', 'expense'
  UNION ALL SELECT '6-60202', 'Bensin, Tol dan Parkir - Umum', 'expense', 'expense'
  UNION ALL SELECT '6-60203', 'Perbaikan & Pemeliharaan', 'expense', 'expense'
  UNION ALL SELECT '6-60204', 'Perjalanan Dinas - Umum', 'expense', 'expense'
  UNION ALL SELECT '6-60205', 'Makanan', 'expense', 'expense'
  UNION ALL SELECT '6-60206', 'Komunikasi - Umum', 'expense', 'expense'
  UNION ALL SELECT '6-60207', 'Iuran & Langganan', 'expense', 'expense'
  UNION ALL SELECT '6-60208', 'Asuransi', 'expense', 'expense'
  UNION ALL SELECT '6-60209', 'Legal & Profesional', 'expense', 'expense'
  UNION ALL SELECT '6-60210', 'Beban Manfaat Karyawan', 'expense', 'expense'
  UNION ALL SELECT '6-60211', 'Sarana Kantor', 'expense', 'expense'
  UNION ALL SELECT '6-60212', 'Pelatihan & Pengembangan', 'expense', 'expense'
  UNION ALL SELECT '6-60213', 'Beban Piutang Tak Tertagih', 'expense', 'expense'
  UNION ALL SELECT '6-60214', 'Pajak dan Perizinan', 'expense', 'expense'
  UNION ALL SELECT '6-60215', 'Denda', 'expense', 'expense'
  UNION ALL SELECT '6-60216', 'Pengeluaran Barang Rusak', 'expense', 'expense'
  UNION ALL SELECT '6-60217', 'Listrik', 'expense', 'expense'
  UNION ALL SELECT '6-60218', 'Air', 'expense', 'expense'
  UNION ALL SELECT '6-60219', 'IPL', 'expense', 'expense'
  UNION ALL SELECT '6-60220', 'Langganan Software', 'expense', 'expense'
  UNION ALL SELECT '6-60300', 'Beban Kantor', 'expense', 'expense'
  UNION ALL SELECT '6-60301', 'Alat Tulis Kantor & Printing', 'expense', 'expense'
  UNION ALL SELECT '6-60302', 'Bea Materai', 'expense', 'expense'
  UNION ALL SELECT '6-60303', 'Keamanan dan Kebersihan', 'expense', 'expense'
  UNION ALL SELECT '6-60304', 'Supplies dan Material', 'expense', 'expense'
  UNION ALL SELECT '6-60305', 'Pemborong', 'expense', 'expense'
  UNION ALL SELECT '6-60400', 'Biaya Sewa - Bangunan', 'expense', 'expense'
  UNION ALL SELECT '6-60401', 'Biaya Sewa - Kendaraan', 'expense', 'expense'
  UNION ALL SELECT '6-60402', 'Biaya Sewa - Operasional', 'expense', 'expense'
  UNION ALL SELECT '6-60403', 'Biaya Sewa - Lain - lain', 'expense', 'expense'
  UNION ALL SELECT '6-60500', 'Penyusutan - Bangunan', 'expense', 'expense'
  UNION ALL SELECT '6-60501', 'Penyusutan - Perbaikan Bangunan', 'expense', 'expense'
  UNION ALL SELECT '6-60502', 'Penyusutan - Kendaraan', 'expense', 'expense'
  UNION ALL SELECT '6-60503', 'Penyusutan - Mesin & Peralatan', 'expense', 'expense'
  UNION ALL SELECT '6-60504', 'Penyusutan - Peralatan Kantor', 'expense', 'expense'
  UNION ALL SELECT '6-60599', 'Penyusutan - Aset Sewa Guna Usaha', 'expense', 'expense'
  UNION ALL SELECT '7-70000', 'Pendapatan Bunga - Bank', 'income', 'other_income'
  UNION ALL SELECT '7-70001', 'Pendapatan Bunga - Deposito', 'income', 'other_income'
  UNION ALL SELECT '7-70002', 'Pendapatan Komisi - Barang Konsinyasi', 'income', 'other_income'
  UNION ALL SELECT '7-70003', 'Pembulatan', 'income', 'other_income'
  UNION ALL SELECT '7-70099', 'Pendapatan Lain - lain', 'income', 'other_income'
  UNION ALL SELECT '8-80000', 'Beban Bunga', 'expense', 'other_expense'
  UNION ALL SELECT '8-80001', 'Provisi', 'expense', 'other_expense'
  UNION ALL SELECT '8-80002', '(Laba)/Rugi Pelepasan Aset Tetap', 'expense', 'other_expense'
  UNION ALL SELECT '8-80100', 'Penyesuaian Persediaan', 'expense', 'other_expense'
  UNION ALL SELECT '8-80999', 'Beban Lain - lain', 'expense', 'other_expense'
  UNION ALL SELECT '9-90000', 'Beban Pajak - Kini', 'expense', 'other_expense'
  UNION ALL SELECT '9-90001', 'Beban Pajak - Tangguhan', 'expense', 'other_expense'
) v
JOIN account_categories c ON c.business_unit = 'b2b' AND c.value = v.cat;
